apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
spec:
  selector:
    app: kafka-manager
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30009
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
#        image: solsson/kafka-manager@sha256:da602758fd542139284d1d106e7dfed78898e0f1eb9756597ab9aee8cfccd763
        image: sheepkiller/kafka-manager
        ports:
        - containerPort: 80
        env:
        - name: ZK_HOSTS
          value: zk-0.zk-svc.default.svc.cluster.local:2181,zk-1.zk-svc.default.svc.cluster.local:2181,zk-2.zk-svc.default.svc.cluster.local:2181
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=80
