---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0.kafka-svc
spec:
  ports:
  - port: 9093
    targetPort: 9093
---
kind: Endpoints
apiVersion: v1
metadata:
 name: kafka-0.kafka-svc
subsets:
 - addresses:
     - ip: 10.240.0.4
   ports:
     - port: 9093    